### ISSUE TITLE
Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by juliapolbach** [ignocide/ig-scrap#1]
Hi! I'm just getting that error and can't figure out what could be the problem.
Your scrapper is so cool, thanks!

```
TypeError: Cannot read property 'status' of undefined
    at new RequestError (.../node_modules/ig-scrap/crawler/model/RequestError.js:4:26)
    at /.../node_modules/ig-scrap/crawler/index.js:67:14
```

**Comment by ignocide** [comment]
i found a change Instagram's origin data's struct and data.. thx

**Comment by ignocide** [comment]
fix that, 
version up plx
thx again
